### PR TITLE
Remove name of outdated RC

### PR DESCRIPTION
**Pull request by milbrandt**
At the linked page only sonarqube-fsharp-plugin-1.0.3-sources.jar is available, which will also expire in next month.

### CODE REVIEW

**Comment by milbrandt** [comment]
@jmecosta it seems like your URL [http://jmecsoftware.com](http://jmecsoftware.com) is no longer online, isn't it? Maybe you would like to update then the organization info and url also.

**Review by jmecosta — APPROVED** [review]
thanks for the update :)

**Comment by jmecosta** [comment]
http://jmecsoftware.com  doesnt make sense anymore! so i will have everything here in github,.

**Comment by milbrandt** [comment]
In pom.xml line 20 there is still the orgnization URL http://jmecsoftware.com

**Pull request merged**
